version: '3'
services:
  redis-server:
    image: 'redis'
    networks:
      - devops
  node-app:
    build: .
    ports:
      - '8080:8081'
    depends_on:
      - redis-server
    networks:
      - devops
networks:
  devops:
    name: devops
    driver: bridge
